global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'beast-monitoring'
    instance: 'prometheus'

# Alerting configuration (placeholder for future use)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files: []

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - Beast system metrics (CPU, RAM, disk, network)
  - job_name: 'node-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'beast'

  # cAdvisor - Docker container metrics
  - job_name: 'cadvisor'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          instance: 'beast-docker'
